name: Quarto Website Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Quarto and tinytex
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.1/quarto-1.6.1-linux-amd64.deb
        sudo dpkg -i quarto-1.6.1-linux-amd64.deb
        sudo apt-get install -f  # To fix missing dependencies
        quarto install tinytex

    - name: Render Quarto Website
      run: |
        quarto render

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
